# Generated by Django 5.0.6 on 2026-06-25 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '浏览'), ('like', '点赞'), ('favorite', '收藏'), ('comment', '评论'), ('share', '分享'), ('search', '搜索'), ('watch', '观看时长')], db_index=True, max_length=20, verbose_name='行为类型')),
                ('search_query', models.CharField(blank=True, default='', max_length=200, verbose_name='搜索关键词')),
                ('value', models.FloatField(default=1.0, help_text='浏览=1, 点赞=2, 收藏=3, 评论=4, 分享=5; 观看时长为实际秒数', verbose_name='行为数值')),
                ('source', models.CharField(blank=True, default='', help_text='如: index, detail, search, recommend', max_length=50, verbose_name='来源')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='行为时间')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.category', verbose_name='关联分类')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='videos.video', verbose_name='关联视频')),
            ],
            options={
                'verbose_name': '用户行为日志',
                'verbose_name_plural': '用户行为日志',
                'db_table': 'recommend_action_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_action_user_time'), models.Index(fields=['video', 'action'], name='idx_action_video_type')],
            },
        ),
        migrations.CreateModel(
            name='VideoTagWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, verbose_name='标签')),
                ('weight', models.FloatField(default=0.5, help_text='0~1 之间的浮点数，表示视频在该标签上的特征强度', verbose_name='权重')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_weights', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频标签权重',
                'verbose_name_plural': '视频标签权重',
                'db_table': 'recommend_video_tag_weight',
                'indexes': [models.Index(fields=['tag', 'weight'], name='idx_tag_weight')],
                'unique_together': {('video', 'tag')},
            },
        ),
    ]
