# Generated by Django 5.0.6 on 2026-06-24 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('note', models.CharField(blank=True, default='', help_text='添加个人备注（可选）', max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'interactions_favorite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'interactions_like',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='评论内容（最多 2000 字）', max_length=2000, verbose_name='评论内容')),
                ('is_approved', models.BooleanField(default=True, help_text='是否已审核通过，未审核的评论前台不显示', verbose_name='是否审核通过')),
                ('likes_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='评论时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent', models.ForeignKey(blank=True, help_text='回复哪条评论（为空表示顶级评论）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interactions.comment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'interactions_comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
