# Generated by Django 5.0.6 on 2026-06-24 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='发表评论的用户', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(help_text='评论所属的视频', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video', verbose_name='关联视频'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(help_text='收藏的用户', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='video',
            field=models.ForeignKey(help_text='被收藏的视频', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='videos.video', verbose_name='视频'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(help_text='点赞的用户', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='like',
            name='video',
            field=models.ForeignKey(help_text='被点赞的视频', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video', verbose_name='视频'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('video', 'user'), name='unique_video_user_favorite', violation_error_message='不能重复收藏同一视频'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('video', 'user'), name='unique_video_user_like', violation_error_message='不能重复点赞同一视频'),
        ),
    ]
