# Generated by Django 5.0.6 on 2026-06-25 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Danmaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='弹幕文本内容（最多 500 字）', max_length=500, verbose_name='弹幕内容')),
                ('time_seconds', models.FloatField(help_text='弹幕在视频时间轴上的位置（单位：秒，支持小数）', verbose_name='出现时间(秒)')),
                ('type', models.CharField(choices=[('scroll', '滚动弹幕'), ('top', '顶部弹幕'), ('bottom', '底部弹幕')], default='scroll', max_length=10, verbose_name='弹幕类型')),
                ('color', models.CharField(default='#FFFFFF', help_text='十六进制颜色代码，如 #FF0000', max_length=7, verbose_name='弹幕颜色')),
                ('font_size', models.IntegerField(default=25, help_text='弹幕字体大小（单位：px）', verbose_name='字体大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发送时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user', models.ForeignKey(blank=True, help_text='匿名弹幕可为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danmaku_set', to=settings.AUTH_USER_MODEL, verbose_name='发送用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danmaku_set', to='videos.video', verbose_name='关联视频')),
            ],
            options={
                'verbose_name': '弹幕',
                'verbose_name_plural': '弹幕',
                'db_table': 'danmaku_danmaku',
                'ordering': ['time_seconds', 'created_at'],
                'indexes': [models.Index(fields=['video', 'time_seconds'], name='idx_danmaku_video_time')],
            },
        ),
    ]
