# Generated by Django 5.0.6 on 2026-06-24 08:05

import apps.videos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：科技、教育、娱乐、音乐', max_length=50, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(help_text='用于 URL 中代替中文名称，如 "technology"', max_length=100, unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, default='', help_text='Bootstrap Icons 等 CSS 类名', max_length=100, verbose_name='图标CSS类')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小，排列越靠前', verbose_name='排序序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, help_text='选择父分类，留空则为顶级分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='videos.category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '视频分类',
                'verbose_name_plural': '视频分类',
                'db_table': 'videos_category',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='请填写视频标题（最多 200 字）', max_length=200, verbose_name='视频标题')),
                ('description', models.TextField(blank=True, default='', help_text='详细描述视频内容（支持 Markdown 格式，最多 5000 字）', max_length=5000, verbose_name='视频描述')),
                ('tags', models.CharField(blank=True, default='', help_text='多个标签用逗号分隔，如：Python, Django, 教程', max_length=500, verbose_name='标签')),
                ('video_file', models.FileField(help_text='支持的格式：MP4, MOV, AVI, MKV', upload_to=apps.videos.models.video_file_upload_path, verbose_name='视频源文件')),
                ('thumbnail', models.ImageField(blank=True, help_text='建议尺寸 16:9，如 1280x720 像素', null=True, upload_to=apps.videos.models.video_thumbnail_upload_path, verbose_name='封面图')),
                ('duration', models.FloatField(default=0.0, help_text='视频时长（秒），上传时由 FFprobe 自动获取', verbose_name='视频时长')),
                ('file_size', models.BigIntegerField(default=0, help_text='文件大小（字节）', verbose_name='文件大小')),
                ('transcoded_files', models.JSONField(blank=True, default=dict, help_text='存储转码后各分辨率文件的路径', verbose_name='转码文件')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='视频被播放的次数', verbose_name='播放量')),
                ('likes_count', models.PositiveIntegerField(default=0, editable=False, help_text='通过点赞记录实时统计', verbose_name='点赞数')),
                ('favorites_count', models.PositiveIntegerField(default=0, editable=False, help_text='通过收藏记录实时统计', verbose_name='收藏数')),
                ('comments_count', models.PositiveIntegerField(default=0, editable=False, help_text='通过评论记录实时统计', verbose_name='评论数')),
                ('status', models.CharField(choices=[('pending', '待转码'), ('transcoding', '转码中'), ('published', '已发布'), ('failed', '转码失败'), ('private', '私密'), ('blocked', '已下架')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('allow_comment', models.BooleanField(default=True, verbose_name='允许评论')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('category', models.ForeignKey(blank=True, help_text='选择视频所属分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.category', verbose_name='所属分类')),
                ('uploader', models.ForeignKey(help_text='视频的上传用户', on_delete=django.db.models.deletion.CASCADE, related_name='videos_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'videos_video',
                'ordering': ['-created_at'],
            },
        ),
    ]
